name = "create-zero"
author = "wawwior"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72018e187c19d1dab630c14efe6849f80bf218f7daa4917ab58fb1d09be4e851"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
