name = "create-zero"
author = "wawwior"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a58c87b53f9dbb5038b8f214e67b2971928c4f1a736eaa09480f1ee7d53b42c2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
