name = "create-zero"
author = "wawwior"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c1800d5f77ac1abe45fb46d2952407a1ced5f45aff93ecb5c567b639239776b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
